# Generated by Django 5.0.7 on 2024-07-21 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0002_director'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieinfo',
            name='success',
            field=models.TextField(default='no data'),
        ),
    ]
