# Generated by Django 5.0.7 on 2024-07-27 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0003_movieinfo_success'),
    ]

    operations = [
        migrations.CreateModel(
            name='Censorinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.TextField()),
                ('Person', models.CharField(max_length=30)),
            ],
        ),
    ]
