# Generated by Django 5.0.7 on 2024-07-27 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0004_censorinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='censorinfo',
            old_name='Person',
            new_name='Certifiedby',
        ),
        migrations.AddField(
            model_name='movieinfo',
            name='poster',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='censorinfo',
            name='rating',
            field=models.CharField(max_length=10),
        ),
    ]
